# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ROCconvexhull <- function(scores, classes) {
    .Call(`_credittree_ROCconvexhull`, scores, classes)
}

EmpCreditScoringCpp <- function(scores, classes, p0, p1, ROI) {
    .Call(`_credittree_EmpCreditScoringCpp`, scores, classes, p0, p1, ROI)
}

